on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/backtest.yml
      - strategies/*

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      strategies: "${{ steps.info.outputs.strategies }}"
      lastmonth: "${{ steps.info.outputs.lastmonth }}"
    steps:
      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - id: info
        shell: bash
        run: |
          strategies=$(awk -F '[ (]' '/\(IStrategy\):/{print $2}' strategies/* | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          echo "strategies=${strategies}" | tee -a ${GITHUB_OUTPUT}
          echo "thismonth=$(date -u +'%Y%m')" | tee -a ${GITHUB_OUTPUT}
          echo "lastmonth=$(date -u +'%Y%m' -d '-1 month')" | tee -a ${GITHUB_OUTPUT}

  backtest:
    runs-on: ubuntu-latest
    needs: info
    strategy:
      matrix:
        exchange:
          - binanceus
        strategy: ${{ fromJSON(needs.info.outputs.strategies) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          path: user_data

      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          ref: "data/${{ matrix.exchange }}/${{ needs.info.outputs.lastmonth }}"
          path: user_data/data/${{ matrix.exchange }}

      - id: backtest
        shell: bash
        run: |
          function freqtrade {
            docker run --rm -v "./user_data:/freqtrade/user_data" freqtradeorg/freqtrade:stable $@
          }
          freqtrade backtesting --strategy ${{ matrix.strategy }} --starting-balance 10000 --timeframe 5m -c user_data/backtest_config/${{ matrix.exchange }}.json -c user_data/backtest_config/common.json --fee 0.012 --export signals
