on:
  workflow_dispatch:
    inputs:
      exchange:
        description: 'Specify one or more specific exchanges to test. csv'
        required: false
        default: 'binanceus'
      strategy:
        description: 'Specify one or more specific strategies to test. csv'
        required: false
        default: ''
      timedata:
        description: 'Specify one or more timeranges to test. csv'
        required: false
        default: '202412'
  push:
    branches:
      - main
    paths:
      - .github/workflows/backtest.yml
      - strategies/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  repository-projects: read

jobs:
  info:
    runs-on: ubuntu-24.04
    outputs:
      exchanges: "${{ steps.info.outputs.exchanges }}"
      strategies: "${{ steps.info.outputs.strategies }}"
      strategy_batch: "${{ steps.info.outputs.strategy_batch }}"
      timedata: "${{ steps.info.outputs.timedata }}"
    steps:
      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - id: info
        shell: bash
        run: |
          #exchanges=$(ls -1 backtest_config | awk -F '.' '!/^common/{print $1}' | sort | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          exchanges='["binanceus"]'
          strategies=$(awk -F '[ (]' '/\(IStrategy\):/{print $2}' strategies/*.py | sort -u | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          timedata=$((date -u +'%Y%m' -d '-1 month' ; date -u +'%Y%m' -d '2022-06-01'; date -u +'%Y%m' -d '2024-11-01') | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          [ -n "${{ github.event.inputs.exchange }}" ] && exchanges=$(echo '${{ github.event.inputs.exchange }}' | tr ',' '\n' | sort | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          [ -n "${{ github.event.inputs.strategy }}" ] && strategies=$(echo '${{ github.event.inputs.strategy }}' | tr ',' '\n' | sort | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          [ -n "${{ github.event.inputs.timedata }}" ] && timedata=$(echo '${{ github.event.inputs.timedata }}' | tr ',' '\n' | sort | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          strategy_count=$(echo "${strategies}" | jq -c --raw-output '.|length')
          exchange_count=$(echo "${exchanges}" | jq -c --raw-output '.|length')
          timedata_count=$(echo "${timedata}" | jq -c --raw-output '.|length')
          max_batch_count=$(( 256 / (${exchange_count} * ${timedata_count}) ))
          strategy_batch_size=$(( (${strategy_count}+${max_batch_count}-1) / ${max_batch_count} ))
          strategy_batch=$(echo "${strategies}" | jq -c --raw-output --arg batch_size "${strategy_batch_size}" '_nwise($batch_size|tonumber)|tojson' | jq -c --raw-input -s '[split("\n")[]|select(length>0)]')
          echo "exchanges=${exchanges}" | tee -a ${GITHUB_OUTPUT}
          echo "strategies=${strategies}" | tee -a ${GITHUB_OUTPUT}
          echo "strategy_batch=${strategy_batch}" | tee -a ${GITHUB_OUTPUT}
          echo "timedata=${timedata}" | tee -a ${GITHUB_OUTPUT}

  backtest:
    runs-on: ubuntu-24.04
    needs: info
    strategy:
      fail-fast: false
      matrix:
        exchange: ${{ fromJSON(needs.info.outputs.exchanges) }}
        strategies: ${{ fromJSON(needs.info.outputs.strategy_batch) }}
        timedata: ${{ fromJSON(needs.info.outputs.timedata) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          path: user_data

      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          ref: "data/${{ matrix.exchange }}/${{ matrix.timedata }}"
          path: user_data/data/${{ matrix.exchange }}

      - id: backtest
        shell: bash
        timeout-minutes: 15
        run: |
          echo "::group::Preload docker image"
          docker pull -q freqtradeorg/freqtrade:stable
          echo "::endgroup::"
          mkdir -p artifacts/backtest/${{ matrix.timedata }}-${{ matrix.exchange }}
          strategy_key=$(echo '${{ matrix.strategies }}${{ matrix.timedata }}' | md5sum | cut -d ' ' -f1)
          function freqtrade {
            docker run --entrypoint "/freqtrade/user_data/docker/entrypoint.sh" --rm -v "./user_data:/freqtrade/user_data" freqtradeorg/freqtrade:stable $@
            sudo chown -R $(id -u):$(id -g) ./user_data
            sudo chown -R $(id -u):$(id -g) ./user_data/.git/config
            sudo chown -R $(id -u):$(id -g) ./user_data/data/${{ matrix.exchange }}/.git/config
          }
          STRATEGIES=( $(echo '${{ matrix.strategies }}' | jq -c --raw-output '.[]') )
          echo "::group::list-data --show-timerange"
          freqtrade list-data --show-timerange -c user_data/backtest_config/common.json -c user_data/backtest_config/${{ matrix.exchange }}.json -c user_data/backtest_config/backtest-pairlist.json
          echo "::endgroup::"
          for strategy in ${STRATEGIES[@]}; do
            echo "::group::Backtest ${strategy}"
            freqtrade backtesting --recursive-strategy-search --strategy-list ${strategy} --starting-balance 1000 --timeframe 1m -c user_data/backtest_config/common.json -c user_data/backtest_config/${{ matrix.exchange }}.json -c user_data/backtest_config/backtest-pairlist.json --export signals --export-filename user_data/backtest_results/${{ matrix.exchange }}_${strategy}.json
            jq '.' ./user_data/backtest_results/$(jq -c -r '.latest_backtest' ./user_data/backtest_results/.last_result.json) > ./artifacts/backtest/${{ matrix.timedata }}-${{ matrix.exchange }}/${strategy}.json
            echo "::endgroup::"
          done
          #echo "results_json=$(jq -c --raw-output '.latest_backtest' ./user_data/backtest_results/.last_result.json)" | tee -a ${GITHUB_OUTPUT}
          echo "strategy_key=${strategy_key}" | tee -a ${GITHUB_OUTPUT}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }}-${{ github.run_attempt }}-${{ matrix.exchange }}-${{ steps.backtest.outputs.strategy_key }}
          path: "${{ github.workspace }}/artifacts"
          retention-days: 1

  summary:
    runs-on: ubuntu-24.04
    needs:
      - info
      - backtest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        exchange: ${{ fromJSON(needs.info.outputs.exchanges) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@main
        continue-on-error: true
        with:
          fetch-depth: 1
          ref: "gh-pages"
          path: gh-pages

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
          pattern: ${{ github.run_number }}-${{ github.run_attempt }}-${{ matrix.exchange }}-*
          merge-multiple: true

      - shell: bash
        run: |
          echo "::group::Artifacts"
          find results -type f
          echo "::endgroup::"
          echo "::group::Prep artifacts for storage"
          [ ! -d gh-pages/backtest ] && mkdir gh-pages/backtest
          rsync -av results/backtest/. gh-pages/backtest/.
          echo "::endgroup::"
          for folder in $(find gh-pages/backtest/ -mindepth 1 -maxdepth 1 -type d); do
            echo "::group::Rebuild comparison ${folder}"
            jq -s '[.[] | .strategy_comparison[]] | sort_by(.key)' ${folder}/*.json > ${folder}.json
            echo "::endgroup::"
          done
          jq -s '[.[] | .strategy_comparison[]] | sort_by(.key)' results/backtest/*/*.json > comparison.json

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const rawData = fs.readFileSync('./comparison.json', 'utf8');
            const jsonData = JSON.parse(rawData);
            //jsonData.sort((a,b)=> a.key.charCodeAt(0) - b.key.charCodeAt(0));
            jsonData.sort((a,b)=> b.profit_total_abs - a.profit_total_abs);
            function objectsToMarkdownTable(objects) {
              if (objects.length === 0) return '';

              const header = Object.keys(objects[0]).join(' | ');
              const separator = Object.keys(objects[0]).map(() => '---').join(' | ');
              const rows = objects.map(obj => Object.values(obj).join(' | '));

              return [header, separator, ...rows].join('\n');
            }
            const markdownTable = objectsToMarkdownTable(jsonData);
            core.summary.addRaw(markdownTable, true)
            core.summary.write()

      - name: Push changes
        shell: bash
        run: |
          OPWD=$(pwd)
          set -x
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cd gh-pages
          if [[ $(git status --porcelain . | wc -l) -gt 0 ]]; then
            git add .
            git commit -m "ci: ${{ github.sha }} $(date -u +'%F %T')"
            git push -u origin "$(git branch --show-current):gh-pages"
          fi
          cd ${OPWD}
