on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/download-data.yml
  #schedule:
  #  - cron: '0 0 * * *'

permissions:
  contents: write
  repository-projects: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  download-data:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - exchange: binanceus
            pairs: ".*/USDT"
            timeframes: '1m 3m 5m 15m 30m 1h 2h 4h 6h 8h 12h 1d 3d 1w 1M'
          - exchange: kraken
            pairs: ".*/USDT"
            timeframes: '1m 5m 15m 30m 1h 4h 1d 1w 2w'
            extra: '--dl-trades'
          - exchange: bitcoincom
            pairs: ".*/USDT"
            timeframes: '1m 3m 5m 15m 30m 1h 4h 1d 1w 1M'
          - exchange: kucoin
            pairs: ".*/USDT"
            timeframes: '1m 3m 5m 15m 30m 1h 2h 4h 6h 8h 12h 1d 1w 1M'
    steps:
      - id: info
        shell: bash
        run: |
          LASTMONTH=$(date -u +'%Y%m' -d '-1 month')
          THISMONTH=$(date -u +'%Y%m')
          NEXTMONTH=$(date -u +'%Y%m' -d '+1 month')
          echo "lastmonth=${LASTMONTH}" | tee -a ${GITHUB_OUTPUT}
          echo "thismonth=${THISMONTH}" | tee -a ${GITHUB_OUTPUT}
          echo "nextmonth=${NEXTMONTH}" | tee -a ${GITHUB_OUTPUT}
          mkdir -p user_data/data

      - name: Git checkout
        uses: actions/checkout@main
        continue-on-error: true
        with:
          fetch-depth: 1
          ref: "data/${{ matrix.exchange }}/${{ steps.info.outputs.lastmonth }}"
          path: user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.lastmonth }}

      - name: Git checkout
        uses: actions/checkout@main
        continue-on-error: true
        with:
          fetch-depth: 1
          ref: "data/${{ matrix.exchange }}/${{ steps.info.outputs.thismonth }}"
          path: user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.thismonth }}

      - id: get-data
        shell: bash
        run: |
          function freqtrade {
            docker run --rm -v "./user_data:/freqtrade/user_data" freqtradeorg/freqtrade:stable $@
          }
          [ ! -d "user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.lastmonth }}" ] && mkdir -p "user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.lastmonth }}"
          [ ! -d "user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.thismonth }}" ] && mkdir -p "user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.thismonth }}"
          echo "::group::Download last month"
          freqtrade download-data --exchange ${{ matrix.exchange }} --pairs ${{ matrix.pairs }} --timeframes ${{ matrix.timeframes }} --timerange ${{ steps.info.outputs.lastmonth }}01-${{ steps.info.outputs.thismonth }}01 --datadir user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.lastmonth }} ${{ matrix.extra || '' }}
          echo "::endgroup::"
          echo "::group::Download this month"
          freqtrade download-data --exchange ${{ matrix.exchange }} --pairs ${{ matrix.pairs }} --timeframes ${{ matrix.timeframes }} --timerange ${{ steps.info.outputs.thismonth }}01- --datadir user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.thismonth }} ${{ matrix.extra || '' }}
          echo "::endgroup::"

      - name: Push lastmonth
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: "data/${{ matrix.exchange }}/${{ steps.info.outputs.lastmonth }}"
          publish_dir: ./user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.lastmonth }}
          force_orphan: true

      - name: Push thismonth
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: "data/${{ matrix.exchange }}/${{ steps.info.outputs.thismonth }}"
          publish_dir: ./user_data/data/${{ matrix.exchange }}-${{ steps.info.outputs.thismonth }}
          force_orphan: false
